<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ITI46.TrackingApp.Client-4a6a6de0-665e-4318-9edc-b5ab1ab312f8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.21.5" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.49.0" />
    <PackageReference Include="Grpc.Tools" Version="2.49.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\ITI46.TrackingApp.Server\Protos\models.proto" GrpcServices="Client">
      <Link>Protos\models.proto</Link>
    </Protobuf>
    <Protobuf Include="..\ITI46.TrackingApp.Server\Protos\TrackingService.proto" GrpcServices="Client">
      <Link>Protos\TrackingService.proto</Link>
    </Protobuf>
  </ItemGroup>
</Project>
