<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<AssemblyName>Day3</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.7" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
	  <PackageReference Include="NuGet.Packaging" Version="7.3.1" />
	  <PackageReference Include="NuGet.Protocol" Version="7.3.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\RazorComponentLibrary\RazorComponentLibrary.csproj" />
	</ItemGroup>

</Project>
