// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SignalrD1.Models;

public partial class Message
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Messagebody { get; set; }
}